## Identify Fraud from Enron Email

### Overview

In 2000, Enron was one of the largest companies in the United States. By 2002, it had collapsed into bankruptcy due to widespread corporate fraud. In the resulting Federal investigation, a significant amount of typically confidential information entered into the public record, including tens of thousands of emails and detailed financial data for top executives.

The purpose of this project is to use machine learning skills to identify Enron Employees who may have committed fraud, based on the public Enron financial and email dataset. I have performed an end-to-end process of investigating the data through a machine learning lens.

### Dataset

The data is combined with a hand-generated list of persons of interest in the fraud case, which means individuals who were indicted, reached a settlement or plea deal with the government, or testified in exchange for prosecution immunity.

In [85]:
# %load poi_id.py
#!/usr/bin/python

import sys
import pickle

ospath = 'C:\\Users\\jubin\\Documents\\GitHub\\DAND-Nanodegree\\ud-ml-projects-master\\tools\\'
sys.path.append(ospath)

from feature_format import featureFormat, targetFeatureSplit
from tester import dump_classifier_and_data

### Task 1: Select what features you'll use.
### features_list is a list of strings, each of which is a feature name.
### The first feature must be "poi".
features_list = ['poi', 'salary', 'exercised_stock_options', 'expenses', 'total_payments', 'total_stock_value']  # You will need to use more features

### Load the dictionary containing the dataset
with open("final_project_dataset.pkl", "r") as data_file:
    data_dict = pickle.load(data_file)

In [86]:
import pandas as pd
import numpy as np

enron_data = pd.DataFrame.from_dict(data_dict, orient='index')

In [87]:
enron_data.head()

,salary,to_messages,deferral_payments,total_payments,exercised_stock_options,bonus,restricted_stock,shared_receipt_with_poi,restricted_stock_deferred,total_stock_value,...,loan_advances,from_messages,other,from_this_person_to_poi,poi,director_fees,deferred_income,long_term_incentive,email_address,from_poi_to_this_person
ALLEN PHILLIP K,201955,2902,2869717,4484442,1729541,4175000,126027,1407,-126027,1729541,...,NaN,2195,152,65,False,NaN,-3081055,304805,phillip.allen@enron.com,47
BADUM JAMES P,NaN,NaN,178980,182466,257817,NaN,NaN,NaN,NaN,257817,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
BANNANTINE JAMES M,477,566,NaN,916197,4046157,NaN,1757552,465,-560222,5243487,...,NaN,29,864523,0,False,NaN,-5104,NaN,james.bannantine@enron.com,39
BAXTER JOHN C,267102,NaN,1295738,5634343,6680544,1200000,3942714,NaN,NaN,10623258,...,NaN,NaN,2660303,NaN,False,NaN,-1386055,1586055,NaN,NaN
BAY FRANKLIN R,239671,NaN,260455,827696,NaN,400000,145796,NaN,-82782,63014,...,NaN,NaN,69,NaN,False,NaN,-201641,NaN,frank.bay@enron.com,NaN

In [88]:
print ("There are total {} people in the dataset.".format(enron_data.shape[0]))
print("Out of which {} are POI and {} are Non-POI.".format(enron_data.poi.value_counts()[True],
                                                          enron_data.poi.value_counts()[False]))
print("Total number of email plus financial features are {}.".format(enron_data.columns.shape[0]-1))
print("Label is 'poi' column.")

There are total 146 people in the dataset.
Out of which 18 are POI and 128 are Non-POI.
Total number of email plus financial features are 20.
Label is 'poi' column.

Enron dataset is really messy and has a lot of missing values (NaN). Almost all of the features have missing values and some features have more than 50% of their values missing, as we can see from the frequency of NaN from the table below.
I have converted NaN to 0, to make all the values numeric and train the machine learning algorithm later.

In [89]:
enron_data.describe().transpose()

                          count unique    top freq
salary                      146     95    NaN   51
to_messages                 146     87    NaN   60
deferral_payments           146     40    NaN  107
total_payments              146    126    NaN   21
exercised_stock_options     146    102    NaN   44
bonus                       146     42    NaN   64
restricted_stock            146     98    NaN   36
shared_receipt_with_poi     146     84    NaN   60
restricted_stock_deferred   146     19    NaN  128
total_stock_value           146    125    NaN   20
expenses                    146     95    NaN   51
loan_advances               146      5    NaN  142
from_messages               146     65    NaN   60
other                       146     93    NaN   53
from_this_person_to_poi     146     42    NaN   60
poi                         146      2  False  128
director_fees               146     18    NaN  129
deferred_income             146     45    NaN   97
long_term_incentive         146     53    NaN   80
email_address               146    112    NaN   35
from_poi_to_this_person     146     58    NaN   60

In [90]:
enron_data.replace(to_replace='NaN', value=0, inplace=True)
enron_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
salary,146.0,3.658114e+05,2.203575e+06,0.0,0.00,210596.0,270850.50,26704229.0
to_messages,146.0,1.221589e+03,2.226771e+03,0.0,0.00,289.0,1585.75,15149.0
deferral_payments,146.0,4.387965e+05,2.741325e+06,-102500.0,0.00,0.0,9684.50,32083396.0
total_payments,146.0,4.350622e+06,2.693448e+07,0.0,93944.75,941359.5,1968286.75,309886585.0
exercised_stock_options,146.0,4.182736e+06,2.607040e+07,0.0,0.00,608293.5,1714220.75,311764000.0
bonus,146.0,1.333474e+06,8.094029e+06,0.0,0.00,300000.0,800000.00,97343619.0
restricted_stock,146.0,1.749257e+06,1.089995e+07,-2604490.0,8115.00,360528.0,814528.00,130322299.0
shared_receipt_with_poi,146.0,6.929863e+02,1.072969e+03,0.0,0.00,102.5,893.50,5521.0
restricted_stock_deferred,146.0,2.051637e+04,1.439661e+06,-7576788.0,0.00,0.0,0.00,15456290.0
total_stock_value,146.0,5.846018e+06,3.624681e+07,-44093.0,228869.50,965955.0,2319991.25,434509511.0
expenses,146.0,7.074827e+04,4.327163e+05,0.0,0.00,20182.0,53740.75,5235198.0
loan_advances,146.0,1.149658e+06,9.649342e+06,0.0,0.00,0.0,0.00,83925000.0
from_messages,146.0,3.586027e+02,1.441260e+03,0.0,0.00,16.5,51.25,14368.0
other,146.0,5.854318e+05,3.682345e+06,0.0,0.00,959.5,150606.50,42667589.0
from_this_person_to_poi,146.0,2.428767e+01,7.927821e+01,0.0,0.00,0.0,13.75,609.0
director_fees,146.0,1.942249e+04,1.190543e+05,0.0,0.00,0.0,0.00,1398517.0
deferred_income,146.0,-3.827622e+05,2.378250e+06,-27992891.0,-37926.00,0.0,0.00,0.0
long_term_incentive,146.0,6.646839e+05,4.046072e+06,0.0,0.00,0.0,375064.75,48521928.0
from_poi_to_this_person,146.0,3.822603e+01,7.390112e+01,0.0,0.00,2.5,40.75,528.0

#### Task 2: Remove outliers
Visualization is one of the most powerful tools for finding outliers. Upon plotting salary against bonus, there is an outlier that pops out immediately - 'Total'. The spreadsheet added up all the data points for us and we need to take this point out. Upon closer examination, I found one more entry which is not the name of a real person 'The Travel Agency In The Park'. The entry is dropped from the dataset. The entries which have all the features as 'NaN' are also dropped from the dataset.

In [91]:
#Importing plotly
from plotly import tools
from plotly import plotly
from plotly import graph_objs

#Setting plotly API credentials
tools.set_credentials_file(username='jubinsoni', api_key='yKCkLUthlyqn7oXWf4U2')

#Making scatterplot before the 'TOTAL' outlier removal
with_outlier_total = graph_objs.Scatter(x = enron_data['salary'],
                           y = enron_data['bonus'],
                           text = enron_data.index,
                           mode = 'markers')

#Removing the outlier
enron_data.drop(labels=['TOTAL'], inplace=True)

#Making scatterplot after the 'TOTAL' outlier removal
without_outlier_total = graph_objs.Scatter(x = enron_data['salary'],
                                    y = enron_data['bonus'],
                                    text = enron_data.index,
                                    mode = 'markers')


#Layout the plots together side by side
fig = tools.make_subplots(rows=1, cols=2, subplot_titles=('Before outlier TOTAL removal', 'After outlier TOTAL removal'))
fig.append_trace(with_outlier_total, 1, 1)
fig.append_trace(without_outlier_total, 1, 2)
fig['layout']['xaxis1'].update(title='salary')
fig['layout']['xaxis2'].update(title='salary')
fig['layout']['yaxis1'].update(title='bonus')
fig['layout']['yaxis2'].update(title='bonus')
plotly.iplot(fig)

This is the format of your plot grid:
[ (1,1) x1,y1 ]  [ (1,2) x2,y2 ]

In [92]:
#Making scatterplot before the 'TRAVEL AGENCY' outlier removal
with_outlier_travel = graph_objs.Scatter(x = enron_data['salary'],
                                  y = enron_data['bonus'],
                                  text = enron_data.index,
                                  mode = 'markers')
#drop
enron_data.drop(labels=['THE TRAVEL AGENCY IN THE PARK'], axis=0, inplace=True)

#Making scatterplot after the 'TRAVEL AGENCY' outlier removal
without_outlier_travel = graph_objs.Scatter(x = enron_data['salary'],
                                  y = enron_data['bonus'],
                                  text = enron_data.index,
                                  mode = 'markers')


#Layout the plots together side by side
fig = tools.make_subplots(rows=1, cols=2, subplot_titles=('Before outlier TRAVEL AGENCY removal', 'After outlier TRAVEL AGENCY removal'))
fig.append_trace(with_outlier_travel, 1, 1)
fig.append_trace(without_outlier_travel, 1, 2)
fig['layout']['xaxis1'].update(title='salary')
fig['layout']['xaxis2'].update(title='salary')
fig['layout']['yaxis1'].update(title='bonus')
fig['layout']['yaxis2'].update(title='bonus')
plotly.iplot(fig)

This is the format of your plot grid:
[ (1,1) x1,y1 ]  [ (1,2) x2,y2 ]

### Task 3: Create new feature(s)
Feature Selection / Feature Engineering
In the Task 1, I have already selected the features of interest.
In this section I will focus more on the Feature Engineering.
Feature engineering involves using human intuition to hypothesize what feature might contain pattern that can be exploited using machine learning, coding up the new feature, visualizing and repeating the process again. Our hypothesis here - "POI's sent email to each other at a rate higher than for Non-POI's". I coded up two new features: fraction of emails this person sends to poi (fraction_from_poi) and fraction of emails this person sends to poi (fraction_to_poi).

In [93]:
#Creating new feature(s)
enron_data['fraction_from_poi'] = enron_data['from_poi_to_this_person'].divide(enron_data['to_messages'], fill_value=0)
enron_data['fraction_to_poi'] = enron_data['from_this_person_to_poi'].divide(enron_data['to_messages'], fill_value=0)

#Replacing NaN in new features with 0
enron_data['fraction_from_poi'].fillna(value=0, inplace=True)
enron_data['fraction_to_poi'].fillna(value=0, inplace=True)

In [104]:
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.layouts import row
from bokeh.models import ColumnarDataSource

output_notebook()

colormap = {False: 'blue', True: 'red'}
colors = [colormap[x] for x in enron_data['poi']]

labelmap = {False: 'Non-POI', True: 'POI'}
labels = [labelmap[x] for x in enron_data['poi']]

source = ColumnarDataSource(dict(x1 = enron_data['from_poi_to_this_person'],
                                y1 = enron_data['from_this_person_to_poi'],
                                x2 = enron_data['fraction_from_poi'],
                                y2 = enron_data['fraction_to_poi'],
                                color = colors,
                                label = labels))

#Before feature engineering
s1 = figure(plot_width=450, plot_height=400)
s1.xaxis.axis_label = "no. of emails from POI to this person"
s1.yaxis.axis_label = "no. of emails from this person to POI"
s1.circle('x1', 'y1', size=10, alpha=0.5, color='color', legend='label', source=source)

#After feature engineering
s2 = figure(plot_width=450, plot_height=400)
s2.xaxis.axis_label = 'fraction of emails this person gets from POI'
s2.yaxis.axis_label = 'fraction of emails this person sends to POI'
s2.circle('x2', 'y2', size=10, alpha=0.5, color='color', legend='label', source=source)

show(row(s1, s2))

TypeError: __init__() takes exactly 1 argument (2 given)

In [ ]:
pd.DataFrame(dict(x1 = enron_data['from_poi_to_this_person'],
                                y1 = enron_data['from_this_person_to_poi'],
                                x2 = enron_data['fraction_from_poi'],
                                y2 = enron_data['fraction_to_poi'],
                                color = colors,
                                label = labels))

                            color    label   x1        x2   y1        y2
ALLEN PHILLIP K              blue  Non-POI   47  0.016196   65  0.022398
BADUM JAMES P                blue  Non-POI    0  0.000000    0  0.000000
BANNANTINE JAMES M           blue  Non-POI   39  0.068905    0  0.000000
BAXTER JOHN C                blue  Non-POI    0  0.000000    0  0.000000
BAY FRANKLIN R               blue  Non-POI    0  0.000000    0  0.000000
BAZELIDES PHILIP J           blue  Non-POI    0  0.000000    0  0.000000
BECK SALLY W                 blue  Non-POI  144  0.019686  386  0.052768
BELDEN TIMOTHY N              red      POI  228  0.028532  108  0.013515
BELFER ROBERT                blue  Non-POI    0  0.000000    0  0.000000
BERBERIAN DAVID              blue  Non-POI    0  0.000000    0  0.000000
BERGSIEKER RICHARD P         blue  Non-POI    4  0.010444    0  0.000000
BHATNAGAR SANJAY             blue  Non-POI    0  0.000000    1  0.001912
BIBI PHILIPPE A              blue  Non-POI   23  0.014312    8  0.004978
BLACHMAN JEREMY M            blue  Non-POI   25  0.010101    2  0.000808
BLAKE JR. NORMAN P           blue  Non-POI    0  0.000000    0  0.000000
BOWEN JR RAYMOND M            red      POI  140  0.075350   15  0.008073
BROWN MICHAEL                blue  Non-POI   13  0.008748    1  0.000673
BUCHANAN HAROLD G            blue  Non-POI    0  0.000000    0  0.000000
BUTTS ROBERT H               blue  Non-POI    0  0.000000    0  0.000000
BUY RICHARD B                blue  Non-POI  156  0.044280   71  0.020153
CALGER CHRISTOPHER F          red      POI  199  0.076597   25  0.009623
CARTER REBECCA C             blue  Non-POI   29  0.092949    7  0.022436
CAUSEY RICHARD A              red      POI   58  0.030655   12  0.006342
CHAN RONNIE                  blue  Non-POI    0  0.000000    0  0.000000
CHRISTODOULOU DIOMEDES       blue  Non-POI    0  0.000000    0  0.000000
CLINE KENNETH W              blue  Non-POI    0  0.000000    0  0.000000
COLWELL WESLEY                red      POI  240  0.136519   11  0.006257
CORDES WILLIAM R             blue  Non-POI   10  0.013089    0  0.000000
COX DAVID                    blue  Non-POI    0  0.000000    4  0.039216
CUMBERLAND MICHAEL S         blue  Non-POI    0  0.000000    0  0.000000
...                           ...      ...  ...       ...  ...       ...
SAVAGE FRANK                 blue  Non-POI    0  0.000000    0  0.000000
SCRIMSHAW MATTHEW            blue  Non-POI    0  0.000000    0  0.000000
SHANKMAN JEFFREY A           blue  Non-POI   94  0.029183   83  0.025768
SHAPIRO RICHARD S            blue  Non-POI   74  0.004885   65  0.004291
SHARP VICTORIA T             blue  Non-POI   24  0.007653    6  0.001913
SHELBY REX                    red      POI   13  0.057778   14  0.062222
SHERRICK JEFFREY B           blue  Non-POI   39  0.063622   18  0.029364
SHERRIFF JOHN R              blue  Non-POI   28  0.008786   23  0.007217
SKILLING JEFFREY K            red      POI   88  0.024262   30  0.008271
STABLER FRANK                blue  Non-POI    0  0.000000    0  0.000000
SULLIVAN-SHAKLOVITZ COLLEEN  blue  Non-POI    0  0.000000    0  0.000000
SUNDE MARTIN                 blue  Non-POI   37  0.013978   13  0.004911
TAYLOR MITCHELL S            blue  Non-POI    0  0.000000    0  0.000000
THORN TERENCE H              blue  Non-POI    0  0.000000    0  0.000000
TILNEY ELIZABETH A           blue  Non-POI   10  0.021739   11  0.023913
UMANOFF ADAM S               blue  Non-POI   12  0.108108    0  0.000000
URQUHART JOHN A              blue  Non-POI    0  0.000000    0  0.000000
WAKEHAM JOHN                 blue  Non-POI    0  0.000000    0  0.000000
WALLS JR ROBERT H            blue  Non-POI   17  0.025335    0  0.000000
WALTERS GARETH W             blue  Non-POI    0  0.000000    0  0.000000
WASAFF GEORGE                blue  Non-POI   22  0.055000    7  0.017500
WESTFAHL RICHARD K           blue  Non-POI    0  0.000000    0  0.000000
WHALEY DAVID A               blue  Non-POI    0  0.000000    0  0.000000
WHALLEY LAWRENCE G           blue  Non-POI  186  0.030902   24  0.003987
WHITE JR THOMAS E            blue  Non-POI    0  0.000000    0  0.000000
WINOKUR JR. HERBERT S        blue  Non-POI    0  0.000000    0  0.000000
WODRASKA JOHN                blue  Non-POI    0  0.000000    0  0.000000
WROBEL BRUCE                 blue  Non-POI    0  0.000000    0  0.000000
YEAGER F SCOTT                red      POI    0  0.000000    0  0.000000
YEAP SOON                    blue  Non-POI    0  0.000000    0  0.000000

[144 rows x 6 columns]

In [ ]:
### Store to my_dataset for easy export below.
my_dataset = data_dict

### Extract features and labels from dataset for local testing
data = featureFormat(my_dataset, features_list, sort_keys=True)
labels, features = targetFeatureSplit(data)

### Task 4: Try a varity of classifiers
### Please name your classifier clf for easy export below.
### Note that if you want to do PCA or other multi-stage operations,
### you'll need to use Pipelines. For more info:
### http://scikit-learn.org/stable/modules/pipeline.html

# Provided to give you a starting point. Try a variety of classifiers.
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

### Task 5: Tune your classifier to achieve better than .3 precision and recall 
### using our testing script. Check the tester.py script in the final project
### folder for details on the evaluation method, especially the test_classifier
### function. Because of the small size of the dataset, the script uses
### stratified shuffle split cross validation. For more info: 
### http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.StratifiedShuffleSplit.html

# Example starting point. Try investigating other evaluation techniques!
from sklearn.cross_validation import train_test_split

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

### Task 6: Dump your classifier, dataset, and features_list so anyone can
### check your results. You do not need to change anything below, but make sure
### that the version of poi_id.py that you submit can be run on its own and
### generates the necessary .pkl files for validating your results.

dump_classifier_and_data(clf, my_dataset, features_list)